baseurl: /starter/
permalink: pretty
markdown: kramdown
include: ['_pages']
plugins:
  - jekyll-optional-front-matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "toc"
  -
    scope:
      path: "_pages"
    values:
      layout: "pages"
prose:
  rooturl: '_pages'
  siteurl: 'http://localhost:4000/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
